import { betterAuth } from 'better-auth';
import { prismaAdapter } from 'better-auth/adapters/prisma';
import { PrismaClient } from '@prisma/client';

// Prisma instance dedicated to Better Auth (separate from the NestJS PrismaService).
// Better Auth is instantiated outside the NestJS context, so it cannot use
// dependency injection — it needs its own client.
const prisma = new PrismaClient();

export const auth = betterAuth({
  database: prismaAdapter(prisma, {
    provider: 'postgresql',
  }),

  // Prefix for all auth routes generated by Better Auth
  basePath: '/api/auth',

  secret: process.env.BETTER_AUTH_SECRET,

  // Origins allowed to make cross-origin requests to the API
  trustedOrigins: [process.env.BETTER_AUTH_URL ?? 'http://localhost:3006'],

  emailAndPassword: {
    enabled: true,
    // No auto sign-in after account creation:
    // accounts are created by the admin, not by the user themselves
    autoSignIn: false,
  },

  user: {
    additionalFields: {
      // Business field added to Better Auth's User model.
      // input: false → cannot be provided during public sign-up
      role: {
        type: 'string',
        required: false,
        defaultValue: 'STUDENT',
        input: false,
      },
    },
  },
});

// Inferred type of the Better Auth session (includes user + role).
// Used in the application's guards and decorators.
export type AuthSession = typeof auth.$Infer.Session;
